#!/usr/bin/env php
<?php
date_default_timezone_set("Europe/Madrid");
require_once __DIR__ . "/App.php";


// if defined parameters in Config/config.yaml
// use it, otherwise, take them from console

if ($argc == 2 && in_array($argv[1], array('--debug', '-debug'))) {
    $debug = true;
}else{
    $debug = false;
}

//$params["user"] = isset($argv[1]) ? $argv[1] : null;
//$params["password"] = isset($argv[2]) ? $argv[2] : null;
//$params["owner"] = isset($argv[3]) ? $argv[3] : null;
//$params["repo"] = isset($argv[4]) ? $argv[4] : null;

$app = new App(null,null, $debug );

// old way
//$merge = new Command\Merge(App::config());
//$merge->pullRequest($params);

$merge = new Command\Merge();
$merge->pullRequest();

