    const FORCE_BUILD_CONFIRMATION = false; // true if you want to ensure your CI suite marked this PR as stable
    const MAX_OPEN_PULL_REQUESTS = 25;
    const HIPCHAT_TOKEN = 'e1'; // this is the hipchat token of the room you want to be notified
    const REQUIRED_POSITIVE_REVIEWS = 1; // this is the number of positive reviews you require to merge the pull request

    protected $validPositiveCodeReviewMessages = array(":+1:", "+1");
    protected $validBlockerCodeReviewMessages = array("[B]", "[b]");
    protected $validUatOKMessages = array("UAT OK");

    protected $user = "myUser";
    protected $password = "myPass";
    protected $owner = 'Company';
    protected $repo = 'repo';